name: golangci-lint
on:
  push:
    branches:
    - master
    - dev
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache-dependency-path: "**/*.sum"
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.64.8
        install-mode: cache
        args: --out-format=colored-line-number --timeout=10m --new-from-rev=HEAD~1 --config=./.github/.golangci.yml --verbose --print-issued-lines
        skip-cache: false
      env:
        GOLANGCI_LINT_CACHE: go-lint-cache-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
